package com.example.labs

object CrosswordWordsData {
    
    val russianWords = listOf(
        WordData("КОТ", "Домашний питомец", "Легкий", 3),
        WordData("ДОМ", "Место жительства", "Легкий", 3),
        WordData("КОД", "Набор символов", "Легкий", 3),
        WordData("ТОМ", "Имя или том книги", "Легкий", 3),
        WordData("РОТ", "Часть лица", "Легкий", 3),
        WordData("СОК", "Напиток из фруктов", "Легкий", 3),
        WordData("РЕПА", "Овощ", "Легкий", 4),
        WordData("МАМА", "Родной человек", "Легкий", 4),
        WordData("ПАПА", "Родной человек", "Легкий", 4),
        WordData("РЫБА", "Водное животное", "Легкий", 4),
        WordData("НОГА", "Часть тела", "Легкий", 4),
        WordData("РУКА", "Часть тела", "Легкий", 4),
        WordData("ГЛАЗ", "Орган зрения", "Легкий", 4),
        WordData("УХО", "Орган слуха", "Легкий", 3),
        WordData("НОС", "Орган обоняния", "Легкий", 3),
        WordData("РОЗА", "Красивый цветок", "Легкий", 4),
        WordData("СТОЛ", "Мебель", "Легкий", 4),
        WordData("СТУЛ", "Мебель для сидения", "Легкий", 4),
        WordData("КНИГА", "Источник знаний", "Легкий", 5),
        WordData("ШКОЛА", "Место учебы", "Легкий", 5),
        
        WordData("РЕКА", "Водный поток", "Средний", 4),
        WordData("ЛЕС", "Много деревьев", "Средний", 3),
        WordData("МОРЕ", "Большой водоем", "Средний", 4),
        WordData("ГОРА", "Высокий холм", "Средний", 4),
        WordData("ПОЛЕ", "Открытое пространство", "Средний", 4),
        WordData("ЛУНА", "Спутник Земли", "Средний", 4),
        WordData("ОСА", "Летающее насекомое", "Средний", 3),
        WordData("ПЧЕЛА", "Собирает мед", "Средний", 5),
        WordData("БАБОЧКА", "Красивое насекомое", "Средний", 8),
        WordData("МУРАВЕЙ", "Трудолюбивое насекомое", "Средний", 7),
        WordData("СОБАКА", "Друг человека", "Средний", 6),
        WordData("КОШКА", "Мурлыкающий питомец", "Средний", 5),
        WordData("МЫШЬ", "Маленький грызун", "Средний", 4),
        WordData("ЗАЯЦ", "Быстрый зверек", "Средний", 4),
        WordData("БЕЛКА", "Лесной зверек", "Средний", 5),
        WordData("ЕЖИК", "Колючий зверек", "Средний", 4),
        WordData("МЕДВЕДЬ", "Лесной хозяин", "Средний", 7),
        WordData("ЛОШАДЬ", "Верный друг", "Средний", 6),
        WordData("КОРОВА", "Дает молоко", "Средний", 6),
        WordData("ОВЦА", "Пушистое животное", "Средний", 4),
        WordData("КУРИЦА", "Несет яйца", "Средний", 6),
        WordData("УТКА", "Водоплавающая птица", "Средний", 4),
        WordData("ГУСЬ", "Белая птица", "Средний", 4),
        WordData("ВОРОНА", "Умная птица", "Средний", 6),
        WordData("ВОРОБЕЙ", "Маленькая птичка", "Средний", 7),
        WordData("СИНИЦА", "Желтая птичка", "Средний", 6),
        WordData("ДЕРЕВО", "Высокое растение", "Средний", 6),
        WordData("БЕРЕЗА", "Белоствольное дерево", "Средний", 6),
        WordData("ДУБ", "Могучее дерево", "Средний", 3),
        WordData("ЕЛЬ", "Новогоднее дерево", "Средний", 3),
        WordData("СОСНА", "Хвойное дерево", "Средний", 5),
        WordData("ЯБЛОКО", "Круглый фрукт", "Средний", 6),
        WordData("ГРУША", "Сладкий фрукт", "Средний", 5),
        WordData("ВИШНЯ", "Красная ягода", "Средний", 5),
        WordData("МАЛИНА", "Сладкая ягода", "Средний", 6),
        WordData("КЛУБНИКА", "Красная ягода", "Средний", 8),
        WordData("МОРКОВЬ", "Оранжевый овощ", "Средний", 7),
        WordData("КАПУСТА", "Зеленый овощ", "Средний", 7),
        WordData("ПОМИДОР", "Красный овощ", "Средний", 7),
        WordData("ОГУРЕЦ", "Зеленый овощ", "Средний", 6),
        
        WordData("СЛОН", "Крупное животное", "Сложный", 4),
        WordData("ЛИСА", "Хитрая животное", "Сложный", 4),
        WordData("ВОЛК", "Лесной хищник", "Сложный", 4),
        WordData("СОВА", "Ночная птица", "Сложный", 4),
        WordData("ЛОСЬ", "Лесной великан", "Сложный", 4),
        WordData("ИВА", "Плакучее дерево", "Сложный", 3),
        WordData("ТИГР", "Полосатый хищник", "Сложный", 4),
        WordData("ЗМЕЯ", "Ползучее пресмыкающееся", "Сложный", 4),
        WordData("ОРЁЛ", "Хищная птица", "Сложный", 4),
        WordData("ЗВЕЗДА", "Небесное тело", "Сложный", 6),
        WordData("СОЛНЦЕ", "Центр системы", "Сложный", 6),
        WordData("ПЛАНЕТА", "Небесное тело", "Сложный", 7),
        WordData("КОМЕТА", "Хвостатая звезда", "Сложный", 6),
        WordData("МЕТЕОРИТ", "Падающая звезда", "Сложный", 8),
        WordData("ГАЛАКТИКА", "Скопление звезд", "Сложный", 9),
        WordData("КОСМОС", "Бесконечное пространство", "Сложный", 6),
        WordData("РАКЕТА", "Космический корабль", "Сложный", 6),
        WordData("КОСМОНАВТ", "Покоритель космоса", "Сложный", 9),
        WordData("ТЕЛЕСКОП", "Прибор для звезд", "Сложный", 8),
        WordData("ОКЕАН", "Огромный водоем", "Сложный", 5),
        WordData("КОНТИНЕНТ", "Большая суша", "Сложный", 9),
        WordData("ВУЛКАН", "Огненная гора", "Сложный", 6),
        WordData("ЗЕМЛЕТРЯСЕНИЕ", "Дрожь земли", "Сложный", 13),
        WordData("УРАГАН", "Сильный ветер", "Сложный", 6),
        WordData("ТОРНАДО", "Вихревой ветер", "Сложный", 7),
        WordData("МОЛНИЯ", "Электрический разряд", "Сложный", 6),
        WordData("ГРОМ", "Звук молнии", "Сложный", 4),
        WordData("РАДУГА", "Разноцветная дуга", "Сложный", 6),
        WordData("ТУЧА", "Темное облако", "Сложный", 5),
        WordData("ОБЛАКО", "Белое на небе", "Сложный", 6),
        WordData("ДОЖДЬ", "Вода с неба", "Сложный", 5),
        WordData("СНЕГ", "Белое покрывало", "Сложный", 4),
        WordData("ЛЕД", "Замерзшая вода", "Сложный", 3),
        WordData("ГРАД", "Ледяные шарики", "Сложный", 4),
        WordData("ИНЕЙ", "Зимний налет", "Сложный", 4),
        WordData("МОРОЗ", "Холодная погода", "Сложный", 5),
        WordData("ЖАРА", "Очень тепло", "Сложный", 4),
        WordData("ТЕПЛО", "Приятная температура", "Сложный", 5),
        WordData("ХОЛОД", "Низкая температура", "Сложный", 5),
        WordData("ВЕТЕР", "Движение воздуха", "Сложный", 5),
        WordData("БУРЯ", "Сильный ветер", "Сложный", 4),
        WordData("ШТОРМ", "Морская буря", "Сложный", 5),
        WordData("ЦУНАМИ", "Волна-убийца", "Сложный", 6),
        WordData("НАВОДНЕНИЕ", "Разлив воды", "Сложный", 10),
        WordData("ЗАСУХА", "Отсутствие дождя", "Сложный", 6),
        WordData("ПОЖАР", "Огонь-разрушитель", "Сложный", 5),
        WordData("ЛАВИНА", "Снежная масса", "Сложный", 6),
        WordData("ОПОЛЗЕНЬ", "Смещение грунта", "Сложный", 8)
    )

    val englishWords = listOf(
        WordData("CAT", "Domestic pet", "Easy", 3),
        WordData("DOG", "Man's best friend", "Easy", 3),
        WordData("HOME", "Place to live", "Easy", 4),
        WordData("CODE", "Set of symbols", "Easy", 4),
        WordData("MOUTH", "Part of face", "Easy", 5),
        WordData("JUICE", "Fruit drink", "Easy", 5),
        WordData("MOM", "Parent", "Easy", 3),
        WordData("DAD", "Parent", "Easy", 3),
        WordData("FISH", "Water animal", "Easy", 4),
        WordData("LEG", "Body part", "Easy", 3),
        WordData("HAND", "Body part", "Easy", 4),
        WordData("EYE", "Vision organ", "Easy", 3),
        WordData("EAR", "Hearing organ", "Easy", 3),
        WordData("NOSE", "Smell organ", "Easy", 4),
        WordData("ROSE", "Beautiful flower", "Easy", 4),
        WordData("TABLE", "Furniture", "Easy", 5),
        WordData("CHAIR", "Sitting furniture", "Easy", 5),
        WordData("BOOK", "Source of knowledge", "Easy", 4),
        WordData("SCHOOL", "Place to study", "Easy", 6),
        
        WordData("RIVER", "Water flow", "Medium", 5),
        WordData("FOREST", "Many trees", "Medium", 6),
        WordData("SEA", "Large water body", "Medium", 3),
        WordData("MOUNTAIN", "High hill", "Medium", 8),
        WordData("FIELD", "Open space", "Medium", 5),
        WordData("MOON", "Earth's satellite", "Medium", 4),
        WordData("BEE", "Honey collector", "Medium", 3),
        WordData("BUTTERFLY", "Beautiful insect", "Medium", 9),
        WordData("ANT", "Hardworking insect", "Medium", 3),
        WordData("MOUSE", "Small rodent", "Medium", 5),
        WordData("RABBIT", "Fast animal", "Medium", 6),
        WordData("SQUIRREL", "Forest animal", "Medium", 8),
        WordData("HEDGEHOG", "Spiky animal", "Medium", 8),
        WordData("BEAR", "Forest owner", "Medium", 4),
        WordData("HORSE", "Loyal friend", "Medium", 5),
        WordData("COW", "Gives milk", "Medium", 3),
        WordData("SHEEP", "Fluffy animal", "Medium", 5),
        WordData("CHICKEN", "Lays eggs", "Medium", 7),
        WordData("DUCK", "Water bird", "Medium", 4),
        WordData("GOOSE", "White bird", "Medium", 5),
        WordData("CROW", "Smart bird", "Medium", 4),
        WordData("SPARROW", "Small bird", "Medium", 7),
        WordData("TREE", "Tall plant", "Medium", 4),
        WordData("BIRCH", "White tree", "Medium", 5),
        WordData("OAK", "Mighty tree", "Medium", 3),
        WordData("SPRUCE", "Christmas tree", "Medium", 6),
        WordData("PINE", "Coniferous tree", "Medium", 4),
        WordData("APPLE", "Round fruit", "Medium", 5),
        WordData("PEAR", "Sweet fruit", "Medium", 4),
        WordData("CHERRY", "Red berry", "Medium", 6),
        WordData("RASPBERRY", "Sweet berry", "Medium", 9),
        WordData("STRAWBERRY", "Red berry", "Medium", 10),
        WordData("CARROT", "Orange vegetable", "Medium", 6),
        WordData("CABBAGE", "Green vegetable", "Medium", 7),
        WordData("TOMATO", "Red vegetable", "Medium", 6),
        WordData("CUCUMBER", "Green vegetable", "Medium", 8),
        
        WordData("ELEPHANT", "Large animal", "Hard", 8),
        WordData("FOX", "Cunning animal", "Hard", 3),
        WordData("WOLF", "Forest predator", "Hard", 4),
        WordData("OWL", "Night bird", "Hard", 3),
        WordData("ELK", "Forest giant", "Hard", 3),
        WordData("WILLOW", "Weeping tree", "Hard", 6),
        WordData("TIGER", "Striped predator", "Hard", 5),
        WordData("SNAKE", "Slithering reptile", "Hard", 5),
        WordData("EAGLE", "Predatory bird", "Hard", 5),
        WordData("STAR", "Celestial body", "Hard", 4),
        WordData("SUN", "Center of system", "Hard", 3),
        WordData("PLANET", "Celestial body", "Hard", 6),
        WordData("COMET", "Tailed star", "Hard", 5),
        WordData("METEORITE", "Falling star", "Hard", 9),
        WordData("GALAXY", "Star cluster", "Hard", 6),
        WordData("SPACE", "Infinite expanse", "Hard", 5),
        WordData("ROCKET", "Spacecraft", "Hard", 6),
        WordData("ASTRONAUT", "Space explorer", "Hard", 9),
        WordData("TELESCOPE", "Star instrument", "Hard", 9),
        WordData("OCEAN", "Huge water body", "Hard", 5),
        WordData("CONTINENT", "Large land", "Hard", 9),
        WordData("VOLCANO", "Fire mountain", "Hard", 7),
        WordData("EARTHQUAKE", "Ground shake", "Hard", 10),
        WordData("HURRICANE", "Strong wind", "Hard", 9),
        WordData("TORNADO", "Whirlwind", "Hard", 7),
        WordData("LIGHTNING", "Electric discharge", "Hard", 9),
        WordData("THUNDER", "Lightning sound", "Hard", 7),
        WordData("RAINBOW", "Colorful arc", "Hard", 7),
        WordData("CLOUD", "Dark cloud", "Hard", 5),
        WordData("RAIN", "Water from sky", "Hard", 4),
        WordData("SNOW", "White blanket", "Hard", 4),
        WordData("ICE", "Frozen water", "Hard", 3),
        WordData("HAIL", "Ice balls", "Hard", 4),
        WordData("FROST", "Cold weather", "Hard", 5),
        WordData("HEAT", "Very warm", "Hard", 4),
        WordData("WARMTH", "Pleasant temperature", "Hard", 6),
        WordData("COLD", "Low temperature", "Hard", 4),
        WordData("WIND", "Air movement", "Hard", 4),
        WordData("STORM", "Strong wind", "Hard", 5),
        WordData("TSUNAMI", "Killer wave", "Hard", 6),
        WordData("FLOOD", "Water overflow", "Hard", 5),
        WordData("DROUGHT", "No rain", "Hard", 7),
        WordData("FIRE", "Destructive fire", "Hard", 4),
        WordData("AVALANCHE", "Snow mass", "Hard", 9),
        WordData("LANDSLIDE", "Ground shift", "Hard", 9)
    )

    data class WordData(
        val word: String,
        val clue: String,
        val difficulty: String,
        val length: Int
    )
}

